name: CI

on:
  pull_request:
  push:
    branches: ['main', 'development']

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - name: Local cache
      uses: actions/cache@v2
      with:
        path: /nix/store
        key: "${{ runner.os }}-nix-cache"

    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - uses: cachix/cachix-action@v10
      with:
        name: flora-pm

    - run: nix-build nix/ci.nix
    - run: nix-shell --run "echo OK"

    - name: Configure environment
      run: |
        echo '/usr/lib/postgresql/12/bin/' >> $GITHUB_PATH
        echo "/nix/var/nix/profiles/per-user/$USER/profile/bin" >> "$GITHUB_PATH"
        echo "/nix/var/nix/profiles/default/bin" >> "$GITHUB_PATH"
        echo 'NIX_PATH="nixpkgs=channel:nixos-unstable"' >> "$GITHUB_ENV"
        echo '$HOME/.ghcup/bin' >> $GITHUB_PATH
        echo 'HOME/.cabal/bin' >> $GITHUB_PATH
        echo 'HOME/.local/bin' >> $GITHUB_PATH

    - name: Running hlint
      run: nix-shell --run './.github/workflows/hlint-runner.sh'

    - name: Running stylish-haskell
      run: nix-shell --run './.github/workflows/stylish-haskell-runner.sh'
